### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by BuckTheWeasel** [UpcraftLP/Respawn-Location-Picker#3]
1.12.2 Minecraft
Forge 14.23.1.2594
(no Sponge installed)

What happend ? 
Join server  use command /kill or be killed by mobs( i dont have a bed placed yet)
then it crashes and connection is lost then you can not join anymore on server because it keeps on deadscreen.

errorlog here : https://pastebin.com/rrmkWmgs

(Only Localworlds Works fine Singleplayer)

**Comment by UpcraftLP** [comment]
Issue is fixed in
- [v1.2.3](https://minecraft.curseforge.com/projects/respawn-location-picker/files/2528686 "Download on CurseForge")  (MC 1.12.X)
- [v1.1.3](https://minecraft.curseforge.com/projects/respawn-location-picker/files/2528685 "Download on CurseForge")  (MC 1.11.2)
- [v1.0.2](https://minecraft.curseforge.com/projects/respawn-location-picker/files/2528682 "Download on CurseForge") (MC 1.10.2)

Thanks for reporting ;)
